name: Automerge
on:
  push:

    branches: [ develop ]

jobs:
  job1:
    name: Pruebas
    runs-on: ubuntu-latest
    steps:
      - name: Checkout de repositorio
        uses: actions/checkout@v2
      - name: Configuración de entorno de python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'

    #  - name: Create branch
    #    uses: peterjgrainger/action-create-branch@v2.0.1
    #    env:
    #      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #    with:
    #      # The branch to create
    #      branch: 'release-candidate2'  
      - name: Correr pruebas 1
        id: correr-pruebas1
        run: python -m unittest -v test_persona.py    
    
   
  automerge:
    name: Automerge
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@4536e8847eb62fe2f0ee52c8fa92d17aa97f932f"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: ""

