name: Pruebas unitarias
on:
  push:
    branches: [ master ]
jobs:
  job1:
    name: Pruebas
    runs-on: ubuntu-latest
    steps:
    - name: Checkout de repositorio
      uses: actions/checkout@v2
    - name: Configuración de entorno de python
      uses: actions/setup-python@v2
      with:
          python-version: '3.7'
    - name: Correr pruebas 1
      id: correr-pruebas1
      run: python -m unittest -v test_persona.py
    - name: Correr pruebas 2
      id: correr-pruebas2
      run: python -m unittest -v test_persona.py 
    - name: Creacion release
      uses: actions/upload-release-asset@v1.0.2
      env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
         upload_url: ${{ steps.create_release.outputs.upload_url }}
         asset_path: target/${{ needs.version.outputs.jar-name }}
         asset_name: ${{ needs.version.outputs.release-jar-name }}
         asset_content_type: application/java-archive  
